name: Scrapy Spider Workflow

on: [push]

jobs:
  run-scrapy-spider:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Scrapy
      run: |
        python -m pip install --upgrade pip
        pip install scrapy

    - name: Run Scrapy Spider
      run: |
        cd padelscraper
        scrapy crawl playerspider -O players.json

    - name: Upload JSON file
      uses: actions/upload-artifact@v3
      with:
        name: players-json
        path: padelscraper/players.json
